# Generated by Django 3.2.6 on 2021-11-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Источник заяки')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Источник заявки',
                'verbose_name_plural': 'Источники заявок',
            },
        ),
    ]
