# Generated by Django 3.2.6 on 2021-08-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210818_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, error_messages={'unique': 'Такой email уже существует'}, max_length=50, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(error_messages={'unique': 'Такой номер уже существует'}, max_length=50, unique=True, verbose_name='Телефон'),
        ),
    ]
