# Generated by Django 3.2.6 on 2021-09-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210820_0003'),
        ('customer', '0003_auto_20210824_2209'),
    ]

    operations = [
    ]
