# Generated by Django 3.2.6 on 2021-08-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210825_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='article.rubric', verbose_name='Рубрика'),
        ),
    ]
