# Generated by Django 3.2.6 on 2021-11-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_name', models.CharField(max_length=100, verbose_name='Компания')),
                ('folio_link', models.CharField(max_length=100, verbose_name='Ссылка')),
                ('folio_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Загрузка обложки')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
