# Generated by Django 3.2.6 on 2021-11-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folio',
            name='folio_link',
            field=models.CharField(max_length=100, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='folio',
            name='folio_name',
            field=models.CharField(max_length=100, verbose_name='Компания'),
        ),
    ]
