# Generated by Django 3.2.6 on 2021-08-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_service_name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('main_service_price', models.CharField(max_length=100, verbose_name='Цена')),
                ('main_service_comment', models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание услуги')),
                ('main_service_slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуга',
            },
        ),
    ]
