# Generated by Django 3.2.6 on 2021-08-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_auto_20210818_1954'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'В обработке'), (2, 'На рассмотрении'), (3, 'Отменен'), (4, 'Завершен')], default=1, null=True, verbose_name='Статус заявки')),
                ('read', models.BooleanField(default=False, verbose_name='Отметить как прочитанное')),
                ('comment', models.TextField(blank=True, max_length=255, null=True, verbose_name='Дополнительный комментарий')),
                ('rec_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('meeting_date', models.DateField(blank=True, null=True, verbose_name='Дата встречи')),
                ('main_service', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_service', to='service.mainservice', verbose_name='Услуга')),
                ('сustomer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_customer', to='customer.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
